language: node_js

node_js:
  - "7"

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 +extension RANDR > /dev/null 2>&1 &
